from main import db
from models import db as dbmodel, Cargas, TiposMovimiento, Movimientos
from sqlalchemy import func

from datetime import datetime, date

dbmodel.create_all()

j = Cargas(date=datetime.utcnow(), fecha_carga=datetime(2019, 12, 25), odometro=10917,emblema='Petropar Aeropuerto', precio=6390, monto_carga=201215)
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(), fecha_carga=datetime(2020, 1, 8), odometro=11262, emblema='Petropar Nu Guazu', precio=6740, monto_carga=290036)
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(), fecha_carga=datetime(2020, 1, 23), odometro=11593, emblema='Petropar Aeropuerto', precio=6740, monto_carga=268097)
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=1, month=2, year=2020), odometro=11769, emblema='Estacion de Servicio', precio=6390, monto_carga=127238) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=2, month=2, year=2020), odometro=12162, emblema='Estacion de Servicio', precio=6540, monto_carga=213000) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=7, month=2, year=2020), odometro=12587, emblema='Estacion de Servicio', precio=6270, monto_carga=230000) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=9, month=2, year=2020), odometro=13019, emblema='Estacion de Servicio', precio=6390, monto_carga=220136) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=21, month=2, year=2020), odometro=13364, emblema='Estacion de Servicio', precio=6390, monto_carga=258297) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=29, month=2, year=2020), odometro=13634, emblema='Estacion de Servicio', precio=6390, monto_carga=214883) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=3, month=4, year=2020), odometro=13927, emblema='Estacion de Servicio', precio=6390, monto_carga=235000) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=13, month=6, year=2020), odometro=14189, emblema='Estacion de Servicio', precio=6040, monto_carga=210029) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=26, month=7, year=2020), odometro=14576, emblema='Estacion de Servicio', precio=6040, monto_carga=270000) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=2, month=9, year=2020), odometro=14994, emblema='Estacion de Servicio', precio=6040, monto_carga=247888) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=18, month=10, year=2020), odometro=15389, emblema='Estacion de Servicio', precio=6040, monto_carga=275007) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=29, month=11, year=2020), odometro=15784, emblema='Estacion de Servicio', precio=6040, monto_carga=250000) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=25, month=12, year=2020), odometro=16104, emblema='Estacion de Servicio', precio=6040, monto_carga=234497) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=31, month=1, year=2021), odometro=16443, emblema='Estacion de Servicio', precio=5790, monto_carga=228080) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=5, month=3, year=2021), odometro=16832, emblema='Estacion de Servicio', precio=6440, monto_carga=260498) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=6, month=4, year=2021), odometro=17133, emblema='Estacion de Servicio', precio=6440, monto_carga=257793) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=23, month=5, year=2021), odometro=17496, emblema='Estacion de Servicio', precio=6440, monto_carga=256125) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=4, month=7, year=2021), odometro=17886, emblema='Estacion de Servicio', precio=6820, monto_carga=260176) 
dbmodel.session.add(j)
dbmodel.session.commit()
j = Cargas(date=datetime.utcnow(),fecha_carga=datetime(day=8, month=8, year=2021), odometro=18292, emblema='Estacion de Servicio', precio=7220, monto_carga=342569) 
dbmodel.session.add(j)
dbmodel.session.commit()


t = TiposMovimiento(tipo='INDEFINIDO')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Automovil')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Combustible')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Educacion')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Farmacia')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Food')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Interes')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Libros')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Ocio')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Pago')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Peluqueria')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Perro')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Ropa')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Seguro')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='Supermercado')
dbmodel.session.add(t)
dbmodel.session.commit()
t = TiposMovimiento(tipo='USA')
dbmodel.session.add(t)
dbmodel.session.commit()

m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 2), descripcion='Almuerzo milas', monto_operacion=110000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 5), descripcion='reyes Maia', monto_operacion=75000,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 5), descripcion='reyes ahijadas', monto_operacion=221560,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 8), descripcion='Pago manual', monto_operacion=-515121,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 9), descripcion='La italiana', monto_operacion=110000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 12), descripcion='S6 Casa', monto_operacion=520233,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 13), descripcion='Pago manual', monto_operacion=-652500,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 16), descripcion='Monte libano', monto_operacion=122000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 17), descripcion='Bebidas', monto_operacion=46000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 20), descripcion='Merienda CTJ', monto_operacion=87568,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 21), descripcion='Seg.de canc.Deuda', monto_operacion=10784,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 21), descripcion='IVA Seg.de canc.Deuda', monto_operacion=1078,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 22), descripcion='Acuarela kitchen', monto_operacion=44000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 23), descripcion='Pago manual', monto_operacion=-962000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 23), descripcion='Vino, queso, tonica', monto_operacion=62400,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 24), descripcion='Vitaminas Vero', monto_operacion=93618,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 24), descripcion='Quiero fruta', monto_operacion=42000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 24), descripcion='Bellini', monto_operacion=68000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 27), descripcion='Sancor(3/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 28), descripcion='Pago manual', monto_operacion=-1956250,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 28), descripcion='Super del mes', monto_operacion=510451,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 31), descripcion='Petrobras Sol', monto_operacion=228080,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 31), descripcion='brunch', monto_operacion=126000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 31), descripcion='helado moztaza', monto_operacion=33500,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 1, 31), descripcion='Forever 21', monto_operacion=18900,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 1), descripcion='Desayuno la costa', monto_operacion=36000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 1), descripcion='Pago Manual', monto_operacion=-1496000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 2), descripcion='Inyeccion desarrollo pulmon', monto_operacion=125273,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 5), descripcion='Cena hamburguesas Mostaza', monto_operacion=162500,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 8), descripcion='BarBas', monto_operacion=55000,  id_tipo_movimiento=11)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 10), descripcion='La italiana', monto_operacion=220000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 12), descripcion='Mingo', monto_operacion=69200,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 12), descripcion='Ferrex', monto_operacion=99900,  id_tipo_movimiento=1)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 12), descripcion='HP1', monto_operacion=105000,  id_tipo_movimiento=8)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 12), descripcion='Ropa cumple Maia', monto_operacion=110500,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 13), descripcion='Grosso', monto_operacion=129000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 13), descripcion='Super cumple Maia', monto_operacion=295896,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 14), descripcion='Heladitos', monto_operacion=47200,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 14), descripcion='Torta', monto_operacion=109750,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 15), descripcion='repisas sala', monto_operacion=45500,  id_tipo_movimiento=1)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 18), descripcion='colitis', monto_operacion=93581,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 19), descripcion='megamylase, pañal', monto_operacion=139430,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 19), descripcion='Ensa de fruta', monto_operacion=16000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 19), descripcion='Mingo', monto_operacion=45000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 20), descripcion='pilsen ñande', monto_operacion=107500,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 21), descripcion='UltraAcai', monto_operacion=54000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 23), descripcion='Seg.De Canc.Deuda', monto_operacion=8216,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 23), descripcion='IVA Seg.De Canc.Deuda', monto_operacion=822,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 24), descripcion='Restaurant la Costa', monto_operacion=35000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 24), descripcion='Pago Manual', monto_operacion=-830000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 25), descripcion='Pago Manual', monto_operacion=-1736250,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 25), descripcion='Faja Vero', monto_operacion=437000,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 25), descripcion='Toalla tela bata', monto_operacion=74600,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 25), descripcion='Sancor(4/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 25), descripcion='Compras del mes', monto_operacion=525828,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 2, 26), descripcion='Tenido Vero', monto_operacion=576000,  id_tipo_movimiento=11)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 2), descripcion='Pago Manual', monto_operacion=-600000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 3), descripcion='test covid', monto_operacion=600000,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 3), descripcion='café la costa', monto_operacion=16000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 4), descripcion='cuota1/3', monto_operacion=75758,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 4), descripcion='Pago Manual', monto_operacion=-1200000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 5), descripcion='Enex España', monto_operacion=260498,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 6), descripcion='Farmacia', monto_operacion=157255,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 6), descripcion='cena hospital', monto_operacion=32750,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 6), descripcion='Pago Manual', monto_operacion=-300000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 7), descripcion='parto bebe', monto_operacion=188200,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 7), descripcion='vitaminas', monto_operacion=58700,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 7), descripcion='almuerzo Vero', monto_operacion=173866,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 10), descripcion='laboratorio bebe', monto_operacion=290000,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 11), descripcion='perro antirrabica', monto_operacion=130000,  id_tipo_movimiento=12)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 12), descripcion='pa;ales', monto_operacion=245439,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 16), descripcion='cumple Lucas', monto_operacion=243850,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 19), descripcion='empas migo', monto_operacion=63000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 19), descripcion='spotify', monto_operacion=39714,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 20), descripcion='bahiano', monto_operacion=66000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 20), descripcion='agua saborizada', monto_operacion=10000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 21), descripcion='super pt. 2', monto_operacion=128955,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 22), descripcion='compras exterior', monto_operacion=542,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 23), descripcion='Seg canc. Deuda', monto_operacion=8799,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 23), descripcion='IVA compras exterior', monto_operacion=54,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 23), descripcion='IVA seg. Canc. Deuda', monto_operacion=880,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 23), descripcion='IVA cuota 1/3', monto_operacion=7576,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 26), descripcion='Sancor(5/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 26), descripcion='Pilsen', monto_operacion=107400,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 29), descripcion='mbeju', monto_operacion=37000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 30), descripcion='pañal', monto_operacion=70321,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 3, 30), descripcion='Pago Automatico', monto_operacion=-842000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 1), descripcion='cuota2/3', monto_operacion=75758,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 1), descripcion='IVA cuota2/3', monto_operacion=7576,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 6), descripcion='ENEX ESPAÑA', monto_operacion=257793,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 6), descripcion='chupete', monto_operacion=53700,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 6), descripcion='Panales', monto_operacion=193100,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 6), descripcion='Pago Manual', monto_operacion=-2726445,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 7), descripcion='Atlas mas', monto_operacion=-193100,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 8), descripcion='Carter-s', monto_operacion=364224,  id_tipo_movimiento=16)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 10), descripcion='Bahiano', monto_operacion=47000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 10), descripcion='Compras del mes', monto_operacion=380565,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 12), descripcion='Compras exterior', monto_operacion=4966,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 12), descripcion='IVA Compras exterior', monto_operacion=497,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 14), descripcion='shampoo', monto_operacion=58750,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 14), descripcion='unhas Vero', monto_operacion=70000,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 16), descripcion='birthcontrol', monto_operacion=60600,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 17), descripcion='hambur, cerdo', monto_operacion=319100,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 19), descripcion='Pago Manual', monto_operacion=-360000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 22), descripcion='Compras exterior', monto_operacion=532,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 22), descripcion='IVA Compras exterior', monto_operacion=53,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 22), descripcion='Seg.De Canc.Deuda', monto_operacion=3201,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 22), descripcion='IVA Seg.De Canc.Deuda', monto_operacion=320,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 22), descripcion='Spotify', monto_operacion=38995,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 24), descripcion='La camorra pizza', monto_operacion=143000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 24), descripcion='Almuerzo domingo', monto_operacion=94097,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 26), descripcion='Pago Manual', monto_operacion=-670000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 27), descripcion='Sancor(6/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 4, 29), descripcion='super del mes p/ mayo', monto_operacion=437484,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 1), descripcion='grido', monto_operacion=55000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 1), descripcion='almuerzo', monto_operacion=138833,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 3), descripcion='pañal', monto_operacion=52284,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 3), descripcion='Cuota Anual 3/3', monto_operacion=75757,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 3), descripcion='IVA Cuota Anual 3/3', monto_operacion=7576,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 4), descripcion='Dipiron', monto_operacion=29233,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 4), descripcion='Pago manual', monto_operacion=-1661250,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 6), descripcion='Ley 6380', monto_operacion=3900,  id_tipo_movimiento=16)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 6), descripcion='Ley 6380', monto_operacion=3971,  id_tipo_movimiento=16)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 7), descripcion='Pañales y pastilla', monto_operacion=368903,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 7), descripcion='Combitos', monto_operacion=82000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 8), descripcion='nachos', monto_operacion=39250,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 8), descripcion='TxK bebe', monto_operacion=39150,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 10), descripcion='multiprocesador', monto_operacion=380000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 10), descripcion='Sephora', monto_operacion=255408,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 12), descripcion='Lentes', monto_operacion=220000,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 12), descripcion='Compras Exterior', monto_operacion=3483,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 12), descripcion='IVA Compras Exterior', monto_operacion=348,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 12), descripcion='Dia de la madre', monto_operacion=318670,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 13), descripcion='Focos', monto_operacion=113600,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 14), descripcion='anticonceptivo', monto_operacion=78124,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 14), descripcion='Toalla chechy', monto_operacion=29900,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 14), descripcion='aeropostale mama', monto_operacion=116000,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 14), descripcion='yogures y demas', monto_operacion=149100,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 14), descripcion='carne desayuno', monto_operacion=198800,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 20), descripcion='Ley 6380', monto_operacion=4073,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 20), descripcion='Compras Exterior', monto_operacion=555,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 20), descripcion='IVA Compras Exterior', monto_operacion=56,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 20), descripcion='Nintendo pro controller', monto_operacion=665000,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 20), descripcion='Spotify', monto_operacion=40732,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 22), descripcion='Bahiano', monto_operacion=100000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 23), descripcion='Petropar Aeropuerto', monto_operacion=256125,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 24), descripcion='Seg.De Canc.Deuda', monto_operacion=12269,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 24), descripcion='IVA Seg.De Canc.Deuda', monto_operacion=1227,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 25), descripcion='Pago manual', monto_operacion=-1370000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 26), descripcion='Sancor(7/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 28), descripcion='corta cuticula', monto_operacion=81468,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 28), descripcion='barbas', monto_operacion=55000,  id_tipo_movimiento=11)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 29), descripcion='Super del mes junio', monto_operacion=624900,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 31), descripcion='Desayuno canasta', monto_operacion=132500,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 31), descripcion='Torta', monto_operacion=65000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 31), descripcion='Pizzas la Italiana', monto_operacion=140000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 5, 31), descripcion='Pago manual', monto_operacion=-1501250,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 4), descripcion='Merienda la costa', monto_operacion=47000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 4), descripcion='Remedios congestion', monto_operacion=92636,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 5), descripcion='Saltarin rojo', monto_operacion=465000,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 7), descripcion='Asado albirro', monto_operacion=274350,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 8), descripcion='Patines Maia', monto_operacion=600000,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 11), descripcion='Anticonceptivo', monto_operacion=72574,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 12), descripcion='Costillita grill', monto_operacion=140400,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 19), descripcion='Pañales junio', monto_operacion=182830,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 19), descripcion='Desayuno ddp', monto_operacion=63741,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 19), descripcion='Spotify', monto_operacion=40912,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 18), descripcion='asado ddp', monto_operacion=155995,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 18), descripcion='Atlas mas', monto_operacion=-155995,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 19), descripcion='IVA Spotify', monto_operacion=4091,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 24), descripcion='San Juan ara', monto_operacion=102829,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 23), descripcion='compras exterior', monto_operacion=558,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 23), descripcion='Seg.canc.', monto_operacion=14433,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 23), descripcion='IVA Seg.canc', monto_operacion=1443,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 23), descripcion='Interes corriente', monto_operacion=1883,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 23), descripcion='IVA Interes corriente', monto_operacion=189,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 25), descripcion='Pago manual', monto_operacion=-1620000,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 25), descripcion='Compras del mes', monto_operacion=518538,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 25), descripcion='Descuento Fortis', monto_operacion=-103708,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 26), descripcion='Bahiano', monto_operacion=34000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 27), descripcion='Sancor(8/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 6, 29), descripcion='Pago manual', monto_operacion=-2669250,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 2), descripcion='Coffee & beans', monto_operacion=80000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 2), descripcion='Limpiador nasal', monto_operacion=85786,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 4), descripcion='Petropar Aeropuerto', monto_operacion=260176,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 3), descripcion='Pizzas', monto_operacion=23914,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 3), descripcion='Pizzas', monto_operacion=126171,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 10), descripcion='matambrito pizza', monto_operacion=114250,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 9), descripcion='anticonceptivo', monto_operacion=63296,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 8), descripcion='Mingo', monto_operacion=59100,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 17), descripcion='Bacon', monto_operacion=100000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 19), descripcion='Spotify', monto_operacion=41451,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 19), descripcion='IVA Spotify', monto_operacion=4145,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 20), descripcion='Mantenimiento 18K Km', monto_operacion=690529,  id_tipo_movimiento=2)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 20), descripcion='Pago mant.', monto_operacion=-690529,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 20), descripcion='compra exterior', monto_operacion=565,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 20), descripcion='mbeju, comida perro', monto_operacion=118831,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 20), descripcion='IVA compra exterior', monto_operacion=57,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 22), descripcion='Empanadas', monto_operacion=100500,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 22), descripcion='Seg.De Canc.Deuda', monto_operacion=6787,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 22), descripcion='IVA Seg.De Canc.Deuda', monto_operacion=679,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 22), descripcion='interes corriente', monto_operacion=100,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 26), descripcion='Pago manual', monto_operacion=-430421,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 27), descripcion='Sancor (9/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 26), descripcion='charcuterias', monto_operacion=24250,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 29), descripcion='compras mama', monto_operacion=675400,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 29), descripcion='compras del mes', monto_operacion=605296,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 29), descripcion='cena mcdonalds', monto_operacion=127500,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 29), descripcion='descuento mama', monto_operacion=-135080,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 29), descripcion='descuento mio', monto_operacion=-64920,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 29), descripcion='No se que es', monto_operacion=10,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 7, 30), descripcion='Sbarro', monto_operacion=73500,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 2), descripcion='Pago Manual', monto_operacion=-3182448,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 2), descripcion='Regalos de la amistad', monto_operacion=105250,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 3), descripcion='Regalos de la amistad', monto_operacion=70967,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 4), descripcion='Petrobras Artigas', monto_operacion=50000,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 6), descripcion='Anticonceptivo', monto_operacion=62650,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 7), descripcion='Pizza', monto_operacion=58228,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 8), descripcion='Petropar Aeropuerto', monto_operacion=292569,  id_tipo_movimiento=3)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 8), descripcion='Ultraacai', monto_operacion=61000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 11), descripcion='Headphones JBL', monto_operacion=471240,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 12), descripcion='Zapato Vero', monto_operacion=87500,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 12), descripcion='Almuerzo', monto_operacion=96213,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 12), descripcion='Zapato Bebe', monto_operacion=52500,  id_tipo_movimiento=13)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 13), descripcion='Agustina y DDN', monto_operacion=136300,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 14), descripcion='Cumple ambar', monto_operacion=78950,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 14), descripcion='HP2', monto_operacion=120000,  id_tipo_movimiento=8)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 14), descripcion='Bahiano', monto_operacion=70000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 19), descripcion='Spotify', monto_operacion=41900,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 19), descripcion='IVA Spotify', monto_operacion=4190,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 19), descripcion='Primera comunion', monto_operacion=60500,  id_tipo_movimiento=9)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 20), descripcion='Compras del mes Set.', monto_operacion=738456,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 21), descripcion='Picadas', monto_operacion=19614,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 19), descripcion='Compras exterior', monto_operacion=572,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 19), descripcion='IVA Compras exterior', monto_operacion=57,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 23), descripcion='Promo Fortis', monto_operacion=-147691,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 23), descripcion='Seg.De Canc.Deuda', monto_operacion=8974,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 23), descripcion='IVA Seg.De Canc.Deuda', monto_operacion=897,  id_tipo_movimiento=7)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 24), descripcion='Pago Manual', monto_operacion=-1027300,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 24), descripcion='Maia gripe', monto_operacion=90150,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 26), descripcion='Sancor (10/12)', monto_operacion=385000,  id_tipo_movimiento=14)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 25), descripcion='BarBas', monto_operacion=55000,  id_tipo_movimiento=11)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 27), descripcion='Primera comunion', monto_operacion=153265,  id_tipo_movimiento=15)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 27), descripcion='duoval', monto_operacion=39957,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 28), descripcion='torta', monto_operacion=65000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 28), descripcion='bocaditos mingo', monto_operacion=160000,  id_tipo_movimiento=6)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 29), descripcion='jarabe bebe', monto_operacion=43115,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 30), descripcion='Pago Manual', monto_operacion=-2073249,  id_tipo_movimiento=10)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 8, 31), descripcion='antibioticos', monto_operacion=131800,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()
m = Movimientos(date=datetime.utcnow(), fecha_operacion=date(2021, 9, 3), descripcion='Anticonceptivo', monto_operacion=55480,  id_tipo_movimiento=5)
dbmodel.session.add(m)
dbmodel.session.commit()



#for j in Movimientos.query.all():print(j)
